package org.motechproject.mtraining.domain;

import org.codehaus.jackson.annotate.JsonProperty;
import org.ektorp.support.TypeDiscriminator;

import java.util.List;
import java.util.UUID;

/**
 * Couch document object representing a Chapter.
 * Chapter
 *   + name    : Chapter name
 *   + chapters : List of messages
 *   + quiz      : quiz for the chapter
 *   + description : Chapter description
 *   + contentId   : UUID that for a chapter (different from the _id generated by couch)
 *   + version     : chapter version (a chapter can have multiple versions, different versions of the chapter will have same contentId)
 *   + externalContentId  : Id that points to an external file or resource that is associated with the chapter.For eg. an audio file that is played to the enrollee when the chapter is started
 *   + createdBy    : Author of the chapter
 *   + createdOn    : Date on which chapter was created
 */
@TypeDiscriminator("doc.type === 'Chapter'")
public class Chapter extends Content {

    @JsonProperty
    private String name;

    @JsonProperty
    private String description;

    @JsonProperty
    private List<Message> messages;

    @JsonProperty
    private Quiz quiz;

    Chapter() {
    }

    public Chapter(boolean isActive, String name, String description, String externalId, String createdBy, List<Message> messages, Quiz quiz) {
        super(isActive, externalId, createdBy);
        this.name = name;
        this.description = description;
        this.messages = messages;
        this.quiz = quiz;
    }

    public Chapter(UUID contentId, Integer version, boolean isActive, String name, String description, String externalId, String createdBy, List<Message> messages, Quiz quiz) {
        super(contentId, version, isActive, externalId, createdBy);
        this.name = name;
        this.description = description;
        this.messages = messages;
        this.quiz = quiz;
    }

    public List<Message> getMessages() {
        return messages;
    }

    public Quiz getQuiz() {
        return quiz;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }
}
